### ISSUE TITLE
You probably want [[]] rather than [] to refer to a column of a data frame.

### ISSUE THREAD

**Issue by rpruim** [treytipton4/fuzzybunnies#46]
https://github.com/treytipton4/fuzzybunnies/blob/fca84d9793f6d93f1c701ee8cf86e45cf80b7e11/R/df_apply.R#L27

Test it out on a data frame of your choosing to see what the difference is between `[[ ]]` and `[ ]`.

**Comment by treytipton4** [comment]
I'm trying this, and the function is not working now, and I cannot figure out why. I'm getting this error message when using test():

Error in `if (sapply(.data[[i]], .filter)) .data[[i]] <- .fun(.data[[i]], 
    ...)`: the condition has length > 1

Also, I'm seeing this difference between [] and [[]]

xy[1]
     x
1 1.21
2 2.00
3 3.00
> xy[[1]]
[1] 1.21 2.00 3.00

but I don't necessarily understand why I want [[]] rather than []

**Comment by rpruim** [comment]
[[ ]] gives you one column of your data frame.  [ ] gives you a data frame with one column.  Since you have said that your function should apply to a column (ie, vector) rather than to a 1-column data frame, it is better to do it that way.  Potentially, this could matter for some values of `.fun()`.
